pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_IMAGE_NAME = 'duranka/durant-flask-app'
    }

    stages {
        stage('Clonage') {
            steps {
                git branch: 'main', url: 'https://github.com/djiomodelor/mon_projet_docker.git'
            }
        }

        stage('Image') {
            steps {
                bat 'docker build -t %DOCKER_IMAGE_NAME%:latest .'
            }
        }

        stage('Publication') {
            steps {
                bat 'docker login -u duranka -p VOTRE_MOT_DE_PASSE'
                bat 'docker push %DOCKER_IMAGE_NAME%:latest'
            }
        }
    }
}
