cd C:\Users\DURANT\mon_projet_docker

# Créer un nouveau Jenkinsfile sans BOM
[System.IO.File]::WriteAllText("$PWD\jenkins\Jenkinsfile", @'
pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'duranka/durant-flask-app'
    }

    stages {
        stage('Clonage') {
            steps {
                git branch: 'main', url: 'https://github.com/djiomodelor/mon_projet_docker.git'
            }
        }

        stage('Image') {
            steps {
                bat 'docker build -t duranka/durant-flask-app:latest .'
            }
        }

        stage('Publication') {
            steps {
                bat 'docker login -u duranka -p Durant@123'
                bat 'docker push duranka/durant-flask-app:latest'
            }
        }
    }
}
'@, [System.Text.UTF8Encoding]::new($false))
